wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.6
    cli_version: 0.16.2
    framework: huggingface
    huggingface_version: 4.37.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1707285603.607324
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      3:
      - 23
      4: 3.9.6
      5: 0.16.2
      6: 4.37.2
      8:
      - 1
      - 5
      13: darwin-x86_64
